---

- name: Fail if not macOS
  fail:
    msg: Must be running macOS
  when:
    - ansible_os_family != 'Darwin'

- name: Register Homebrew install state
  stat:
    path: /usr/local/bin/brew
  register: homebrew_brew

- name: Fail if Homebrew is not installed
  fail:
    msg: No Homebrew at `/usr/local/bin/brew`
  when:
    - not homebrew_brew.stat.exists

- name: Install git
  become: false
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
  when:
    - homebrew_brew.stat.exists

- name: Register source gitconfig
  stat:
    path: /Volumes/Shuroo/.gitconfig
  register: source_gitconfig

- name: Copy source gitconfig
  become: false
  copy:
    src: "/Volumes/Shuroo/.gitconfig"
    dest: "~/.gitconfig"
  when:
    source_gitconfig.stat.exists

...
