---

- name: Fail if not macOS
  fail:
    msg: Must be running macOS
  when:
    - ansible_os_family != 'Darwin'

- name: Register Homebrew install state
  stat:
    path: /usr/local/bin/brew
  register: homebrew_brew

- name: Fail if Homebrew is not installed
  fail:
    msg: No Homebrew at `/usr/local/bin/brew`
  when:
    - not homebrew_brew.stat.exists

- name: Install git
  become: false
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
  when:
    - homebrew_brew.stat.exists

- name: Register source gitconfig
  stat:
    path: /Volumes/Shuroo/.gitconfig
  register: source_gitconfig

- name: Register taraget gitconfig
  stat:
    path: ~/.gitconfig
  register: target_gitconfig

- name: Copy source gitconfig
  become: false
  copy:
    src: "/Volumes/Shuroo/.gitconfig"
    dest: "~/.gitconfig"
  when:
    - source_gitconfig.stat.exists
    - not target_gitconfig.stat.exists

- name: Register git user name
  become: false
  shell: git config --global --get user.name
  register: git_user_name_result
  changed_when: false
  failed_when: false

- name: Register git user email
  shell: git config --global --get user.email
  register: git_user_email_result
  changed_when: false
  failed_when: false

- name: Set git user name
  shell: git config --global user.name "{{git_user_name}}"
  when:
    - git_user_name
    - git_user_name_result.stdout != git_user_name

- name: Set git user email
  shell: git config --global user.email "{{git_user_email}}"
  when:
    - git_user_email
    - git_user_email_result.stdout != git_user_email

...
